name: Pylint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install matplotlib
        pip install numpy
        pip install pandas
        pip install pandas-datareader
        pip install python-dateutil
    - name: Analysing the code with pylint
      run: |
        pylint $(find . -name "*.py" | xargs) --disable=C0103 --disable=unused-argument --disable=global-statement\
          --disable=missing-module-docstring

